name: itruda
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pandas==2.1.4
  - PyTorch >= 1.0.0 (with suitable CUDA and CuDNN version)
  - torchvision >= 0.2.2
  - scipy==1.13.1
  - scikit-learn==1.5.2
  - matplotlib==3.9.2